include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    no_default_cases: false
    directives_ordering: false
    unnecessary_lambdas: false
    omit_local_variable_types: false
analyzer:
  plugins:
    - dart_code_metrics
  errors:
    missing_required_param: error
    missing_return: warning

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
