name: rick_and_morty
description: rick andmorty Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  auto_route_generator: ^3.2.3
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_core: ^1.14.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.3
  flutter_secure_storage: ^5.0.2
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  hooks_riverpod: ^1.0.3
  http_mock_adapter: ^0.3.2
  infinite_scroll_pagination: ^3.1.0
  json_serializable: ^6.1.6
  pretty_dio_logger: ^1.1.1
  salomon_bottom_bar: ^3.3.0
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  very_good_analysis: ^2.4.0

import_sorter:
  emojis: true # Optional, defaults to false
  comments: true # Optional, defaults to true

flutter:
  uses-material-design: true
  assets:
    - assets/env/.env.development
    - assets/env/
    - assets/
